baseURL = 'https://topology.work/'
languageCode = 'en-us'
title = 'topology.work'
enableRobotsTXT = true

[outputs]
  home = ["HTML", "RSS"]

[params]
  description = "The work and the work under the work"
